### ISSUE TITLE
Doesn't work for a simple glua obfuscator

### ISSUE THREAD

**Issue by wrefgtzweve** [Vurv78/LuaPro#8]
Obufscator: https://github.com/jkusner/LuaObfuscator
Example code: https://github.com/Jaffies/Jaffies-Anti-Cheat/blob/main/lua/jac/cl_init.lua

Error with example: `Error when running: ../src/lexer/lua.lua:340: Could not parse token ["‪ = "] at line 1, cols 6-6`

Tested on https://vurv78.github.io/LuaPro/web/index.html

**Comment by Vurv78** [comment]
This parses properly in https://github.com/Vurv78/LuaPro/tree/lupa if you still need a parser. @wrefgtzweve
